#!/usr/bin/env bash

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s "Home" -c ~
    exit 0
fi

if ! tmux has-session -t="Home" 2>/dev/null; then
    tmux new-session -ds "Home" -c ~
fi

tmux switch-client -t "Home"
