require("cj-plug-config.plugins")
require("cj-plug-config.lsp")
require("cj-plug-config.treesitter")
require("cj-plug-config.telescope")
require("cj-plug-config.auto-pairs")
require("cj-plug-config.comment-nvim")
require("cj-plug-config.lightline")
require("cj-plug-config.nvim-tree")
